# Generated by Django 3.0.3 on 2021-06-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apidata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='Cover',
        ),
    ]
