# Generated by Django 3.0.3 on 2021-06-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_apidata_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='Cover',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
