# Generated by Django 3.0.3 on 2021-06-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apidata_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='vid_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
