# Generated by Django 3.0.3 on 2021-12-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_apidata_vid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidata',
            old_name='Cover',
            new_name='animetype',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='Home',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='vid_id',
        ),
        migrations.AddField(
            model_name='apidata',
            name='dates',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='apidata',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apidata',
            name='english_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='apidata',
            name='episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apidata',
            name='img_src',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apidata',
            name='members',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apidata',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='apidata',
            name='score_members',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='apidata',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
