# Generated by Django 3.0.3 on 2021-12-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211202_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='animeid',
            field=models.IntegerField(null=True),
        ),
    ]
