# Generated by Django 3.0.3 on 2021-12-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_apidata_animeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='genre',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
